### ISSUE TITLE
Support for drag & drop sorting

### ISSUE THREAD

**Issue by prsebastian** [florianschmitt/ext-token-field#11]
Hi!

have you considered sorting the Tokens by drag &drop? This would be an very useful feature!

Thanks in advance,
Sebastian

**Comment by florianschmitt** [comment]
Hi Sebastian, 

not really, because we didn't need that functionality yet. 
Maybe, if I find the time I will take a look, otherwise I would be happy to review a pull request!

BR
Florian

**Comment by florianschmitt** [comment]
I got curious how to implement DnD with GWT, so I did it ;)

BR Florian
