### ISSUE TITLE
Online demo is offline

### ISSUE THREAD

**Issue by whiteancient** [florianschmitt/ext-token-field#13]
Think the title says it all :)

**Comment by florianschmitt** [comment]
Hi, thanks for the info. I just checked and it seems to be a general problem with the Servint Jelastic cloud environment. They offered a free cloud platform for all Vaadin Add-ons before. Now all Servint Instances of other Vaadin Add-ons are down as well, so maybe they don't offer these free platforms anymore. I will ask in the Vaadin Forum.

**Comment by florianschmitt** [comment]
https://vaadin.com/forum#!/thread/14916631

**Comment by florianschmitt** [comment]
Demo is back online
