### ISSUE TITLE
[Request] Button to show dropdown?

### ISSUE THREAD

**Issue by etemplar** [florianschmitt/ext-token-field#5]
Is it possible to implement combobox-like button on the right side to show dropdown menu with all elements from container? Having to use arrow down key is not very intuitive.

Thanks!

**Comment by florianschmitt** [comment]
Hey, I simply set the display value of the combobox button to 'none', as you can see in exttokenfield.css:

`v-widget.exttokenfield .v-filterselect .v-filterselect-button {
    display: none;
}`

When you set it for example to 'block', it will be visible again.

<img width="954" alt="exttokenfield" src="https://cloud.githubusercontent.com/assets/817148/12761196/393c1a20-c9ea-11e5-9a6b-3251759cb347.PNG">

So you can override this rule, if you define it yourself in your theme (maybe you have to add !important)

Thanks!.
