### ISSUE TITLE
Method to remove all tokenizables at once?

### ISSUE THREAD

**Issue by etemplar** [florianschmitt/ext-token-field#6]
Hello again,

Last one request: is it possible to implement method to simply remove all tokenizables from ExtTokenField? (or I've searched worse than I should have)

Thanks for the awesome addon and pointing out that combobox style thing.

**Comment by florianschmitt** [comment]
Hey, no problem.
You can do it as with any other Vaadin field, by setting the value of the field:

`tokenField.setValue(null);`
or 
`tokenField.setValue(new ArrayList<>());`

Cheers!
